-- Default layout from Playable Piano
MKeyboard:RegisterLayout( "compact", "#musicalk.layout.compact", {
    { button = KEY_A, note = 60 },
    { button = KEY_W, note = 61 },
    { button = KEY_S, note = 62 },
    { button = KEY_E, note = 63 },
    { button = KEY_D, note = 64 },
    { button = KEY_F, note = 65 },
    { button = KEY_T, note = 66 },
    { button = KEY_G, note = 67 },
    { button = KEY_Y, note = 68 },
    { button = KEY_H, note = 69 },
    { button = KEY_U, note = 70 },
    { button = KEY_J, note = 71 },
    { button = KEY_K, note = 72 },
    { button = KEY_O, note = 73 },
    { button = KEY_L, note = 74 },
    { button = KEY_P, note = 75 },
    { button = KEY_SEMICOLON, note = 76 },
    { button = KEY_APOSTROPHE, note = 77 }
} )

-- Expanded layout from Playable Piano
MKeyboard:RegisterLayout( "expanded", "#musicalk.layout.expanded", {
    { button = KEY_1, note = 36 },
    { button = KEY_1, note = 37, requiresShift = true },
    { button = KEY_2, note = 38 },
    { button = KEY_2, note = 39, requiresShift = true },
    { button = KEY_3, note = 40 },
    { button = KEY_4, note = 41 },
    { button = KEY_4, note = 42, requiresShift = true },
    { button = KEY_5, note = 43 },
    { button = KEY_5, note = 44, requiresShift = true },
    { button = KEY_6, note = 45 },
    { button = KEY_6, note = 46, requiresShift = true },
    { button = KEY_7, note = 47 },
    { button = KEY_8, note = 48 },
    { button = KEY_8, note = 49, requiresShift = true },
    { button = KEY_9, note = 50 },
    { button = KEY_9, note = 51, requiresShift = true },
    { button = KEY_0, note = 52 },

    { button = KEY_Q, note = 53 },
    { button = KEY_Q, note = 54, requiresShift = true },
    { button = KEY_W, note = 55 },
    { button = KEY_W, note = 56, requiresShift = true },
    { button = KEY_E, note = 57 },
    { button = KEY_E, note = 58, requiresShift = true },
    { button = KEY_R, note = 59 },
    { button = KEY_T, note = 60 },
    { button = KEY_T, note = 61, requiresShift = true },
    { button = KEY_Y, note = 62 },
    { button = KEY_Y, note = 63, requiresShift = true },
    { button = KEY_U, note = 64 },
    { button = KEY_I, note = 65 },
    { button = KEY_I, note = 66, requiresShift = true },
    { button = KEY_O, note = 67 },
    { button = KEY_O, note = 68, requiresShift = true },
    { button = KEY_P, note = 69 },
    { button = KEY_P, note = 70, requiresShift = true },

    { button = KEY_A, note = 71 },
    { button = KEY_S, note = 72 },
    { button = KEY_S, note = 73, requiresShift = true },
    { button = KEY_D, note = 74 },
    { button = KEY_D, note = 75, requiresShift = true },
    { button = KEY_F, note = 76 },
    { button = KEY_G, note = 77 },
    { button = KEY_G, note = 78, requiresShift = true },
    { button = KEY_H, note = 79 },
    { button = KEY_H, note = 80, requiresShift = true },
    { button = KEY_J, note = 81 },
    { button = KEY_J, note = 82, requiresShift = true },
    { button = KEY_K, note = 83 },
    { button = KEY_L, note = 84 },
    { button = KEY_L, note = 85, requiresShift = true },

    { button = KEY_Z, note = 86 },
    { button = KEY_Z, note = 87, requiresShift = true },
    { button = KEY_X, note = 88 },
    { button = KEY_C, note = 89 },
    { button = KEY_C, note = 90, requiresShift = true },
    { button = KEY_V, note = 91 },
    { button = KEY_V, note = 92, requiresShift = true },
    { button = KEY_B, note = 93 },
    { button = KEY_B, note = 94, requiresShift = true },
    { button = KEY_N, note = 95 },
    { button = KEY_M, note = 96 }
} )

-- Keyboard layout from FL Studio
MKeyboard:RegisterLayout( "fl_studio", "FL Studio", {
    { button = KEY_Z, note = 24 },
    { button = KEY_S, note = 25 },
    { button = KEY_X, note = 26 },
    { button = KEY_D, note = 27 },
    { button = KEY_C, note = 28 },
    { button = KEY_V, note = 29 },
    { button = KEY_G, note = 30 },
    { button = KEY_B, note = 31 },
    { button = KEY_H, note = 32 },
    { button = KEY_N, note = 33 },
    { button = KEY_J, note = 34 },
    { button = KEY_M, note = 35 },

    { button = KEY_Q, note = 36, altButton = KEY_COMMA },
    { button = KEY_2, note = 37, altButton = KEY_L },
    { button = KEY_W, note = 38, altButton = KEY_PERIOD },
    { button = KEY_3, note = 39, altButton = KEY_SEMICOLON },
    { button = KEY_E, note = 40, altButton = KEY_SLASH },
    { button = KEY_R, note = 41 },
    { button = KEY_5, note = 42 },
    { button = KEY_T, note = 43 },
    { button = KEY_6, note = 44 },
    { button = KEY_Y, note = 45 },
    { button = KEY_7, note = 46 },
    { button = KEY_U, note = 47 },
    { button = KEY_I, note = 48 },
    { button = KEY_9, note = 49 },
    { button = KEY_O, note = 50 },
    { button = KEY_0, note = 51 },
    { button = KEY_P, note = 52 },
    { button = KEY_LBRACKET, note = 53 },
    { button = KEY_EQUAL, note = 54 },
    { button = KEY_RBRACKET, note = 55 }
}, 12 )
